site_name: TIGRESS Data Release
nav:
    - Home: index.md
    - Example 1: read_data_1-MHD.ipynb
    - Example 2: read_data_2-chem-CO_lines.ipynb
    - API References: module.md
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [module]
          options:
            docstring_style: "numpy"
            show_source: true
            show_root_heading: true
            heading_level: 2
      watch:
        - module
        - analysis
