site_name: TIGRESS Data Release
nav:
    - Home: index.md
    - Usage: usage.md
    - Example 1: read_data_1-MHD.ipynb
    - Example 2: read_data_2-chem_CO_lines.ipynb
theme:
  name: "material"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: [module, analysis]
          options:
            docstring_style: "numpy"
            show_source: false
      custom_templates: templates
      watch:
        - module
        - analysis
